spring:
  application:
    name: infosystem-client

server:
  port: 8080

# společné – Thymeleaf
spring:
  thymeleaf:
    cache: false        # v prod dej true (viz níže)

# ===== dev =====
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false

server:
  address: 127.0.0.1

backend:
  base-url: http://localhost:8081   # WebClient bude volat sem

logging:
  level:
    root: info
    org.springframework.web: info

# ===== prod =====
---
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true

backend:
  base-url: ${BACKEND_BASE_URL}     # např. http://infosystem:8081 v docker síti
