spring:
  application:
    name: infosystem-client
  thymeleaf:
    cache: false            # v dev/test vypnuto; prod přepíšeme na true
  main:
    banner-mode: "off"

server:
  port: 8080
  address: 0.0.0.0          # naslouchat všude (docker/k8s); v dev přepíšeme na 127.0.0.1
  compression:
    enabled: true

logging:
  level:
    root: info

# Vlastní properties pro WebClient (přepiš v profilech)
backend:
  base-url: http://localhost:8081
  http:
    connect-timeout-ms: 3000
    read-timeout-ms: 5000


# ===== dev =====
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false

server:
  address: 127.0.0.1

backend:
  base-url: http://localhost:8081   # WebClient bude volat sem

logging:
  level:
    root: info
    org.springframework.web: info

# ===== prod =====
---
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true

backend:
  base-url: ${BACKEND_BASE_URL}     # např. http://infosystem:8081 v docker síti
