spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true               # zapnout cache šablon (výkon)

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  compression:
    enabled: true

# V produkci vždy z ENV
backend:
  base-url: ${BACKEND_BASE_URL}              # např. http://infosystem:8081 (docker síť) nebo https://api.example.com
  http:
    connect-timeout-ms: ${BACKEND_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${BACKEND_READ_TIMEOUT_MS:5000}

logging:
  level:
    root: info
