# src/main/resources/application-prod.yml
spring:
  config:
    activate:
      on-profile: prod              # -> aktivuje se pouze při profilu 'prod'

  # === Databáze (PostgreSQL) ===
  datasource:
    url: ${SPRING_DATASOURCE_URL}   # např. jdbc:postgresql://db:5432/infosystem_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:4}
      idle-timeout: 600000          # 10 min
      max-lifetime: 1800000         # 30 min (nižší než pg idle_timeout)
      connection-timeout: 30000     # 30 s
      # volitelné optimalizace pro PG:
      data-source-properties:
        reWriteBatchedInserts: true

  # === JPA/Hibernate ===
  jpa:
    hibernate:
      ddl-auto: validate            # schéma nechte řídit Flyway/Liquibase
    open-in-view: false             # už je v common, ale v prod to chceme určitě
    properties:
      hibernate.jdbc.time_zone: UTC

  # === Flyway (verzované migrace schématu) ===
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true       # při prvním běhu proti existující DB nastav baseline
    clean-disabled: true            # v prod nikdy nečistit

  # === SQL init (seed) – v prod typicky vypnuto ===
  sql:
    init:
      mode: never

  # === CORS (přepiš ENV proměnnou) ===
  mvc:
    cors:
      mappings:
        '[/**]':
          allowed-origins: ${APP_ALLOWED_ORIGINS:https://app.example.com}
          allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
          max-age: 3600

server:
  # V kontejneru běž na všech rozhraních; port si případně přepiš ENV SERVER_PORT
  address: 0.0.0.0
  port: ${SERVER_PORT:8081}
  shutdown: graceful
  # Pokud stojíš za reverzní proxy (Nginx/Traefik), povol správné předávání hlaviček:
  forward-headers-strategy: framework
  compression:
    enabled: true
    min-response-size: 1KB

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus   # prometheus jen pokud ho používáš/scrapuješ
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  # volitelně jiný port jen pro actuator:
  # server:
  #   port: 9090

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.springframework.security: info
  # Loguj na STDOUT (bez souborů) – 12-factor / kontejnery
  # logging.file.name lze nepoužívat

# === Aplikační (business) properties přepínané přes ENV ===
app:
  default-page-size: ${APP_DEFAULT_PAGE_SIZE:20}

# === JWT / tajemství (výhradně z ENV v prod) ===
security:
  jwt:
    secret: ${JWT_SECRET}                       # nastav v CI/Secrets
    expiration-minutes: ${JWT_EXP_MIN:60}
