# src/main/resources/application.yml
# ------------------------------------------------------------
# Společné minimum – platí pro všechny profily (dev/test/prod).
# ------------------------------------------------------------

spring:
  application:
    name: infosystem
  jackson:
    # ISO-8601 místo timestampů
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    # Lepší než default ON (omezuje lazy-loading mimo transakce)
    open-in-view: false
  main:
    # Utiší banner při startu
    banner-mode: "off"
  sql:
    # Init skripty výchozí vypnuto – zapínej v profilu dev/test, pokud chceš seed
    init:
      mode: never

server:
  # Výchozí port; možnost přepsat v profilech přes env SERVER_PORT
  port: 8081
  # Když běží v Dockeru/K8s, naslouchej na všech rozhraních
  address: 0.0.0.0
  # GZIP komprese odpovědí
  compression:
    enabled: true
  error:
    # Bezpečnější výchozí chování chybových zpráv
    include-message: "never"
    include-binding-errors: "never"

management:
  endpoints:
    web:
      # Jen základ (další jako 'prometheus' v prod podle potřeby)
      exposure:
        include: "health,info"
  endpoint:
    health:
      # Detailní zdraví jen pro autorizované (např. actuator user/role)
      show-details: "when_authorized"

logging:
  level:
    # Klidné defaulty; detailnější logování až v dev/test profilech
    root: info

# -----------------------------------------------
# Místo pro tvoje „business“ properties s defaulty
# (přepisuj v profilu dle prostředí)
# -----------------------------------------------
app:
  # stránkování, technické limity apod.
  default-page-size: 20



# ===== dev profil (lokální vývoj) =====
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/infosystem_db
    username: info_user
    password: info_pass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update           # pro vývoj ok; v prod raději validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin

server:
  address: 127.0.0.1

logging:
  level:
    root: info
    org.springframework.security: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# JWT a další tajemství ber z ENV (lokálně můžeš dát .env / IDE Run Config)
security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-override-me}
    expiration-minutes: ${JWT_EXP_MIN:60}


# ===== prod profil (produkce / docker / cloud) =====
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}           # např. jdbc:postgresql://db:5432/school
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate                    # v prod validuj, nemigruj schéma
  sql:
    init:
      mode: never

logging:
  level:
    root: info

security:
  jwt:
    secret: ${JWT_SECRET}                   # nastav v CI/VM
    expiration-minutes: ${JWT_EXP_MIN:60}

